### ISSUE TITLE
PGM Crashes

### ISSUE THREAD

**Issue by stilllearning65** [powerseb/PowerExtract#7]
Every time I run the program it crashes in the same place. Tried 3 different Dump files (Win10_1803, Win10_22H2 & Win11_23H2. They all error in the same place, even re-downloaded pgm..

PS D:\> invoke-powerextract -pathtodmp d:\hex\1803.dmp
DEBUG: Inputfile valid and identified in: d:\hex\1803.dmp
New-Object : Cannot find type [â€TypeName System.IO.FileStream â€ArgumentList]: verify that the assembly containing
this type is loaded.
At D:\Invoke-PowerExtract.ps1:409 char:23
+ ... ileStream = New-Object â€“TypeName System.IO.FileStream â€“ArgumentLi ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand

New-Object : Cannot find type [â€TypeName System.IO.BinaryReader â€ArgumentList]: verify that the assembly containing
this type is loaded.
At D:\Invoke-PowerExtract.ps1:410 char:23
+ ... ileReader = New-Object â€“TypeName System.IO.BinaryReader â€“Argument ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand

The property 'Position' cannot be found on this object. Verify that the property exists and can be set.
At D:\Invoke-PowerExtract.ps1:412 char:9
+         $fileReader.BaseStream.Position=0
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

You cannot call a method on a null-valued expression.
At D:\Invoke-PowerExtract.ps1:413 char:9
+         $Signature = Convert-LitEdian -String ([System.BitConverter]: ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
....

DEBUG: No Crypto Material could be extracted - Script is terminated.

**Comment by stilllearning65** [comment]
I just finished testing this with dump files from Windows 10 v1803 thru Windows 11 v24H2, they all error in the same place. I tried downloading the zip, downloading the raw ps1 and even copy and paste the raw file, all with same results.

[IPE debug Win10_1809.zip](https://github.com/user-attachments/files/19399110/IPE.debug.Win10_1809.zip)

**Comment by powerseb** [comment]
Hi, 

many thanks for the input - as far as I see it this encoding problem seems to be very simular with https://github.com/powerseb/PowerExtract/issues/4 - which can be caused if the content ist not copied with UTF-8 encoding. I tested it with a copy of the raw view of github (https://raw.githubusercontent.com/powerseb/PowerExtract/refs/heads/main/Invoke-PowerExtract.ps1) and had non of the errors. 

The quick and dirty fix if you still have the isse you could search and replace â€“ with - this should fix the functions. I hope this helps.

**Comment by stilllearning65** [comment]
â€“ is nowhere in the script, i also replaced the '-' with '-' and it still fails with the same error. Re-downloaded file, an saved to utf-8, have a "us" keyboard. Can't figure it out. Thanks for the help

**Comment by stilllearning65** [comment]
forgot to add i tried re-downloading [5x], copy -n- paste (with notepad & notepad++) multiple times

**Comment by stilllearning65** [comment]
downloaded raw file and saved as utf-8-bom an it is working. thx
